### PR TITLE
[small]feature/11

### PR DESCRIPTION
**Pull request by josdem**
Implementation [issue 11](https://github.com/josdem/sneakers-world-shopping/issues/11)
- Adding `data-testid` values to validate document structure
- Adding Jest fetch mock to validate product list
- Validating document structure using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

### CODE REVIEW

**Comment by VanshVg** [comment]
Hey @josdem I am bit confused here. It guess you have already implemented it so what do we have to do exactly??

**Comment by josdem** [comment]
> Hey @josdem I am bit confused here. It guess you have already implemented it so what do we have to do exactly??

Hi @VanshVg  happy to clarify here. In the industry, before merging a new feature branch, we create a PR (pull request), and the main reason for doing that is to get feedback from other developers (you are part of those). With that said, I am expecting to happen these options:
- You just approve without comments
- You add some feedback/improvements suggestions and approve
- You detected a wrong implementation / bad practice in this PR therefore you will not approve adding some comments explaining why.

**Comment by VanshVg** [comment]
Hey @josdem I have noticed one issue in product.list.test.js.
In that there are two test functions with same name "render product list".

**Comment by josdem** [comment]
> Hey @josdem I have noticed one issue in product.list.test.js. In that there are two test functions with same name "render product list".

Hi @VanshVg, thanks for taking the time and review the PR. Please notice that on file changes, you will see in red what we removed and in green what we added to the code; therefore, there is no duplicated method, just deletions/additions. If you want to see the complete file, you can use this option. 
view_file

**Comment by VanshVg** [comment]
Oh right my bad, I didn't notice it.
Then everything is good.

**Pull request merged**
